version: "3.9"
services:
  ui:
    platform: "linux/amd64"
    container_name: ui_container
    hostname: UI
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "4000:4000"
    image: t3-app
    restart: always
    environment:
      - DATABASE_URL=file:./db.sqlite
      - UA_URL=https://ua.piper.finance
      - PS_URL=https://ps.piper.finance
      - TP_URL=https://tp.piper.finance
      - TH_URL=https://th.piper.finance
      - NT_URL=https://nt.piper.finance
      - PORT=4000
