version: "3.9"
services:
  ui:
    platform: "linux/amd64"
    container_name: testnet_ui_container
    hostname: testnet_UI
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "4001:4001"
    image: testnet_t3-app
    environment:
      - DATABASE_URL=file:./db.sqlite
      - PORT=4001