import Head from 'next/head';
import { Button } from '@ui/Button/Button';
import { Avatar } from '@ui/Avatar/Avatar';
import { Input } from '@ui/Input/Input';
import { Disclosure } from '@headlessui/react';
import { ChevronUpIcon } from '@heroicons/react/20/solid';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import ERC20Balance from '../state/dashboard/updater';

export default function Home() {
  return (
    <>
      <Head>
        <title>Cross-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <section className="w-full min-w-fit	 max-w-screen-lg	 border p-2 rounded-md border-x-gray-400">
        <table className="table-auto w-full max-w-screen-lg">
          <tbody className="text-sm">
            <Disclosure as="tr" className="rounded-md">
              {({ open }) => (
                <>
                  <Disclosure.Button
                    as="td"
                    className="flex w-full justify-between rounded-lg  text-left text-sm font-medium bg-white  hover:bg-gray-200 focus:outline-none focus-visible:ring focus-visible:ring-purple-500 focus-visible:ring-opacity-75"
                  >
                    <tr className="w-full">
                      <td className="p-2 whitespace-nowrap">
                        <div className="flex items-center">
                          <div className="w-10 h-10 flex-shrink-0 mr-2 sm:mr-3">
                            <img
                              className="rounded-full"
                              src="https://raw.githubusercontent.com/cruip/vuejs-admin-dashboard-template/main/src/images/user-36-05.jpg"
                              width="40"
                              height="40"
                              alt="Alex Shatov"
                            />
                          </div>
                        </div>
                      </td>
                      <td className="p-2 whitespace-nowrap">
                        <div className="text-left">alexshatov@gmail.com</div>
                      </td>
                      <td className="p-2 whitespace-nowrap">
                        <div className="text-left font-medium text-green-500">
                          $2,890.66
                        </div>
                      </td>
                    </tr>

                    <ChevronUpIcon
                      className={`${
                        open ? 'rotate-180 transform' : ''
                      } h-5 w-5 text-gray-500  my-auto mx-4`}
                    />
                  </Disclosure.Button>
                  <Disclosure.Panel
                    as="div"
                    className="px-4 pt-4 pb-2 text-sm text-white-500 border border-gray-300 rounded-md"
                  >
                    <div className="flex items-center">
                      <div className="w-10 h-10 flex-shrink-0 mr-2 sm:mr-3">
                        <img
                          className="rounded-full"
                          src="https://raw.githubusercontent.com/cruip/vuejs-admin-dashboard-template/main/src/images/user-36-05.jpg"
                          width="40"
                          height="40"
                          alt="Alex Shatov"
                        />
                      </div>
                    </div>
                  </Disclosure.Panel>
                </>
              )}
            </Disclosure>
          </tbody>
        </table>
      </section> */}

      <ConnectButton />
      <ERC20Balance />
    </>
  );
}
